"use client"
import { Noticia_Text } from "next/font/google";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';
import { toast,ToastContainer } from 'react-toastify'
import { useState } from 'react'
import { CartContext } from './_context/Cartcontext'
import { ClerkProvider, } from '@clerk/nextjs'

import Header from "./_components/Header";
import Footer from "./_components/Footer";

const inter = Noticia_Text({ subsets: ["latin"], weight: '700' });

// export const metadata = {
//   title: "E-commerce App",

//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [cart, setCart] = useState([])
  return (

    <ClerkProvider>


      <CartContext.Provider value={{ cart, setCart }}>
        
        <html lang="en">
        
        
          <body>
   
            <Header />


            {children}
            
            <Footer />
           <ToastContainer 
            position="top-left"
            autoClose={5000}
           />
          </body>
       
        </html>
        
      </CartContext.Provider>
    </ClerkProvider>

  );

}


